### PR TITLE
Docker Image

### PR DESCRIPTION
**Pull request by hypery2k**
to use the autobuild feature, create hub.docker.com account and follow these instructions:

https://docs.docker.com/docker-hub/builds/

### CODE REVIEW

**Comment by hypery2k** [comment]
you can find an image here: https://cloud.docker.com/repository/docker/hypery2k/backuppc_exporter

**Comment by otwieracz** [comment]
Thank you very much for your contribution! I've got one objection - you've pulled vendor libraries into repository (`src/vendor`) adding hundreds of files into repository - is this intentional and necessary?

**Comment by hypery2k** [comment]
sure, you're right. Shouldn't be there ;)

**Comment by otwieracz** [comment]
@hypery2k, thanks for great work and sorry for it taking so long to merge. :)

**Pull request merged**
